### ISSUE TITLE
Discord component prints errors in tests

### ISSUE THREAD

**Issue by ggwadera** [garageScript/c0d3-app#715]
DiscordBar component storyshot tests prints some errors to the console due to an state update.

```
Warning: An update to DiscordBar inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act

      31 |       )
      32 |       const json = await data.json()
    > 33 |       if ('members' in json) setData(json as discordJSON)
         |                              ^
      34 |       else setData({ members: [], error: 'Something went wrong ;(' })
      35 |     } catch (e) {
      36 |       setData({

at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:68:30)
at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:44:5)
at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15034:9)
at setData (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7129:9)
at getData (components/DiscordBar.tsx:33:30)
```

**Comment by hwong0305** [comment]
This error is caused by the way storybook snapshots are deployed.

Since, we don't snapshots for both storybook components and the pages itself, I recommend to remove storybook init snapshots and write the missing tests ourselves.
