### ISSUE TITLE
Bug: MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by tomrule007** [garageScript/c0d3-app#924]
## Bug

This maybe only a local issue to my machine but I thought I would document it just encase others are having it.

In my server console when running either: `yarn start` or `yarn dev` shortly after first load of the page I am getting this  `MaxListenersExceededWarning: Possible EventEmitter memory leak detected` warning.

running `NODE_OPTIONS='--trace-warnings' yarn dev` i was able to get the stack trace and included it below.

I'm not sure if the logger files are causing the issue or they are just reporting the issue?

## Setup

**commit:**  17e6818350b0d90369f83c58d8b79ccea7348c77 (current master)
**environment**: Local Dev (debian 9 linux)

## Details

```
(node:14074) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:451:17)
    at process.addListener (events.js:467:10)
    at ExceptionHandler.handle (/home/thomas/JS/c0d3-app/node_modules/winston/lib/winston/exception-handler.js:51:15)
    at DerivedLogger.configure (/home/thomas/JS/c0d3-app/node_modules/winston/lib/winston/logger.js:139:23)
    at new Logger (/home/thomas/JS/c0d3-app/node_modules/winston/lib/winston/logger.js:42:10)
    at new DerivedLogger (/home/thomas/JS/c0d3-app/node_modules/winston/lib/winston/create-logger.js:44:7)
    at Object.module.exports [as createLogger] (/home/thomas/JS/c0d3-app/node_modules/winston/lib/winston/create-logger.js:48:18)
    at winstonLogger (webpack-internal:///./helpers/middleware/logger.ts:40:57)
    at Array.__webpack_exports__.default (webpack-internal:///./helpers/middleware/logger.ts:60:18)
    at loop (/home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:69:47)
    at next (/home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:74:13)
    at Function.handle (/home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:77:5)
    at /home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:57:12
    at new Promise (<anonymous>)
    at Function.run (/home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:56:12)
    at nc (/home/thomas/JS/c0d3-app/node_modules/next-connect/dist/index.cjs:14:15)
    at apiResolver (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/api-utils.js:8:7)
    at DevServer.handleApiRequest (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/next-server.js:66:492)
    at async Object.fn (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/next-server.js:58:580)
    at async Router.execute (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/next-server.js:68:1042)
    at async DevServer.handleRequest (/home/thomas/JS/c0d3-app/node_modules/next/dist/next-server/server/next-server.js:32:504)

```

**Comment by tomrule007** [comment]
It appears to be the many calls to `winston.createLogger(..)` that is causing the problem.

With the logger lines commented out (included below) I am no longer getting the error
```
export default (req: LoggedRequest, res: NextApiResponse, next: () => void) => {
  const uid = nanoid()
  // const logger = winstonLogger(uid)
  req.info = (val: any) => {
    // logger.info(processArgs(val))
  }
  req.warn = (val: any) => {
    // logger.warn(processArgs(val))
  }
  req.error = (val: any) => {
    // logger.error(processArgs(val))
  }
  req.requestId = uid
  res.setHeader('c0d3-debug-id', uid)
  next()
}
```
[logger.ts L59-L74](https://github.com/garageScript/c0d3-app/blob/17e6818350b0d90369f83c58d8b79ccea7348c77/helpers/middleware/logger.ts#L59-L74)

**Comment by tomrule007** [comment]
Logflare logs confirm the bug is currently happening in production.

```json
{
  "deploymentId": "dpl_Aq3WLreJsaMbNwY7QJQHPvjpz9J8",
  "host": "c0d3-app-nkcww6vzb-c0d3.vercel.app",
  "id": "1625528177539811943776480127",
  "message": "START RequestId: 7c5e480d-46b5-4d2a-a0d7-85e851e2e8e7 Version: $LATEST\n2021-07-05T23:36:17.588Z\t7c5e480d-46b5-4d2a-a0d7-85e851e2e8e7\tERROR\t(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit\n(Use `node --trace-warnings ...` to show where the warning was created)\nEND RequestId: 7c5e480d-46b5-4d2a-a0d7-85e851e2e8e7\nREPORT RequestId: 7c5e480d-46b5-4d2a-a0d7-85e851e2e8e7\tDuration: 243.41 ms\tBilled Duration: 244 ms\tMemory Size: 1024 MB\tMax Memory Used: 187 MB\t\n",
  "parsedLambdaMessage": {
    "lines": {
      "level": "error",
      "message": "(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit\n(Use `node --trace-warnings ...` to show where the warning was created)",
      "timestamp": "2021-07-05T23:36:17.588Z"
    },
    "parse_status": "full",
    "report": {
      "billed_duration_ms": 244,
      "duration_ms": 243,
      "max_memory_used_mb": 187,
      "memory_size_mb": 1024
    },
    "request_id": "7c5e480d-46b5-4d2a-a0d7-85e851e2e8e7"
  },
  "path": "api/graphql",
  "projectId": "QmXsUqXtwKTu8KDgbNanmnzGXrvJNEwEbvutvu7QRVXWqS",
  "proxy": {
    "clientIp": "",
    "host": "www.c0d3.com",
    "method": "POST",
    "path": "/api/graphql",
    "referer": "https://www.c0d3.com/curriculum/3",
    "region": "iad1",
    "scheme": "https",
    "statusCode": 200,
    "timestamp": 1625528177538,
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
  },
  "requestId": "w8ctq-1625528177538-b7806bfc3bed",
  "source": "lambda",
  "statusCode": 200,
  "timestamp": 1625528177539
}
```

**Comment by tomrule007** [comment]
PR #926 Seems to have handled this issue. See issue #906 for details, closing for now
